---
title: "Download Resources from Drive"
author: "ROSSyndicate"
date: "2023-11-15"
output: html_document
---

```{r}
library(tidyverse)
library(googledrive)

# authorize drive - requires .renviron document with valid email
drive_auth(Sys.getenv("google_email"))

# where to save zips to
zip_dir <- "data/download/zip/"
# where to save unzips to
unzip_dir <- "data/download/"
```

And now get the file list from the google folder.

Get folder id
```{r}
folder <- drive_find(pattern = Sys.getenv("folder_name"))
```

And list files
```{r}
files <- drive_ls(folder$id)
```

And download files to data symlink folder (data symlink is not tracked in GH)
```{r}
download_from_drive <- function(filename, fileid, dest_filepath) {
  drive_download(file = as_id(fileid), path = file.path(dest_filepath, filename))
}

pwalk(list(files$name, 
           files$id, 
           list(zip_dir)),
      download_from_drive
)
```

# Unzip files downloaded from drive

```{r}
zips <- list.files(zip_dir, full.names = T, pattern = '.zip') 

map(zips, function(z){unzip(z, exdir = unzip_dir)})
```

